### ISSUE TITLE
installtion error

### ISSUE THREAD

**Issue by zeev-mindali** [iklein99/homebridge-smartthings#246]
**Describe Your Problem:**

when installing the plugin getting error:

**Logs:**
[install_error.log](https://github.com/iklein99/homebridge-smartthings/files/13889917/install_error.log)

```
Show the Homebridge logs here, remove any sensitive information.
```
npm ERR! code ENOMEM
npm ERR! syscall spawn
npm ERR! errno -12
npm ERR! spawn ENOMEM

**Plugin Config:**
didn't get to it :(

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.5.20
* **Homebridge Version**:  1.7.0
* **Node.js Version**:  18.19.0
* **NPM Version**:  10.2.3
* **Operating System**:  debian 10

**Comment by iklein99** [comment]
It would appear that the device you are running homebridge on doesn’t have enough memory.

**Comment by zeev-mindali** [comment]
i manage to install the plugin.
but i getting now error:
Smartthings Plug (IK)] Could not connect to web hook service: AxiosError: timeout of 90000ms exceeded.  Will retry

the config:
{
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "f8fa9102-c990-4015-XXXX-XXXXXXXXXXXXXX",
            "WebhookToken": "a0c98500-afca-11ee-XXXX-XXXXXXXXXXXXXX",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "PollWindowShadesSeconds": 20,
            "ExposeHumiditySensorForAirConditioners": true,
            "OptionalModeForAirConditioners": "None",
            "platform": "HomeBridgeSmartThings"
        }

and i don't see any device :(

**Comment by zeev-mindali** [comment]
o.k., reinstalled the plugin again, and no error.
but on smartthings (according to kleinsudios.net) i purachse the web token, and follow the steps.
the app show me , setup not completed yet :(

**Comment by zeev-mindali** [comment]
here is the log from hb:

[1/11/2024, 6:18:56 AM] [HB Supervisor] Restarting Homebridge...
[1/11/2024, 6:18:56 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/11/2024, 6:18:56 AM] [HB Supervisor] Starting Homebridge with custom env: {"DEBUG":"DEBUG=HAP-NodeJS:*."}
[1/11/2024, 6:18:56 AM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 5340
[1/11/2024, 6:19:05 AM] Loaded config.json with 33 accessories and 3 platforms.
[1/11/2024, 6:19:05 AM] Loaded 1 cached accessories from cachedAccessories.
[1/11/2024, 6:19:05 AM] ---
[1/11/2024, 6:19:17 AM] Loaded plugin: homebridge-config-ui-x@4.55.1
[1/11/2024, 6:19:17 AM] Registering platform 'homebridge-config-ui-x.config'
[1/11/2024, 6:19:17 AM] ---
[1/11/2024, 6:19:18 AM] Loaded plugin: homebridge-gsh@2.2.0
[1/11/2024, 6:19:18 AM] Registering platform 'homebridge-gsh.google-smarthome'
[1/11/2024, 6:19:18 AM] ---
[1/11/2024, 6:19:44 AM] Loaded plugin: homebridge-mqttthing@1.1.47
[1/11/2024, 6:19:44 AM] Registering accessory 'homebridge-mqttthing.mqttthing'
[1/11/2024, 6:19:44 AM] ---
[1/11/2024, 6:19:45 AM] Loaded plugin: homebridge-smartthings-ik@1.5.20
[1/11/2024, 6:19:45 AM] Registering platform 'homebridge-smartthings-ik.HomeBridgeSmartThings'
[1/11/2024, 6:19:45 AM] ---
[1/11/2024, 6:19:45 AM] Loading 3 platforms...
[1/11/2024, 6:19:45 AM] [Smartthings Plug] Initializing HomeBridgeSmartThings platform...
[1/11/2024, 6:19:45 AM] [Google Smart Home] Initializing google-smarthome platform...
[1/11/2024, 6:19:45 AM] Loading 33 accessories...
[1/11/2024, 6:19:45 AM] [node-10-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-10-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-11-epid-root] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-12-epid-root] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-13-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-13-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-14-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-14-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:46 AM] [node-16-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-16-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-16-epid-3] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-17-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-17-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-17-epid-3] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-3] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-4] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-5] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-6] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-7] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-8] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-9] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-10] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-11] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-12] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-19-epid-13] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-55-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-55-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-55-epid-3] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-56-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-58-epid-1] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [node-58-epid-2] Initializing mqttthing accessory...
[1/11/2024, 6:19:47 AM] [Smartthings Plug] Loading accessory from cache: Samsung AU7172 50 TV
Setup Payload:
X-HM://00253URZJ6JID
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
      │ XXX-XX-XXX │     
    └────────────┘     
                       
[1/11/2024, 6:19:59 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 4827) is running on port 51785.
[1/11/2024, 6:20:01 AM] [Smartthings Plug] Restoring existing accessory from cache: Samsung AU7172 50 TV
[1/11/2024, 6:20:02 AM] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[1/11/2024, 6:20:18 AM] [Smartthings Plug] Samsung AU7172 50 TV is offline
[1/11/2024, 6:20:26 AM] [Google Smart Home] Finished instance discovery
[1/11/2024, 6:20:41 AM] [Google Smart Home] Sending Sync Request

**Comment by zeev-mindali** [comment]
[1/11/2024, 6:27:12 AM] [Smartthings Plug] Could not connect to web hook service: Error: read ECONNRESET.  Will retry
[1/11/2024, 6:31:08 AM] [Smartthings Plug] Could not connect to web hook service: AxiosError: timeout of 90000ms exceeded.  Will retry

**Comment by coryabooth** [comment]
You should delete the Access Token from your post...

**Comment by zeev-mindali** [comment]
there is access token in the post

**Comment by zeev-mindali** [comment]
sent you an email with homebridge logs

**Comment by zeev-mindali** [comment]
removed the token, no change, don't see the devices.
i follow the instructors for detailed log.

**Comment by coryabooth** [comment]
Maybe there was or is a hick up?

I am seeing the same - and I've had this running for a while now (haven't seen these entries before)
![image](https://github.com/iklein99/homebridge-smartthings/assets/5266177/e16853c5-8d9b-4a88-89a6-1c3a88390c4b)

**Comment by iklein99** [comment]
That issue is fixed.  Thanks for bringing it to my attention.

**Comment by zeev-mindali** [comment]
still don't see my devices, sent you logs.
the google home gsh, show the devices, also the alexa plugin

**Comment by zeev-mindali** [comment]
just to be on the safe side.
with your plugin, it takes my homebridge devices and show them in the smartthings?

**Comment by iklein99** [comment]
No.  Just the opposite.  It will add SmartThings devices to Homebridge.

**Comment by coryabooth** [comment]
> just to be on the safe side. with your plugin, it takes my homebridge devices and show them in the smartthings?

You should navigate here:
https://my.smartthings.com/advanced
Verify all your devices and verify they are all "Online"

You should check your Smarthings App - ensure all devices are correct.

Homebridge is a tools to surface Smart Items to Apple Home. (HomeKit)
Apple is notorious for locking their ecosystem, this is a "bridge" to make existing devices compatible.

This plugin only surfaces Smartthings devices.
There are other plugins - Garage Doors, Security Cameras, Doorbells - etc...
This is a plugin is just one of hundreds of different plugins...

Ultimately the goal here is to get your smart devices, no matter where they are running, to show up in Apple Home (or Eve)

If you aren't using Apple Home - or are otherwise fine with SmartThings App (which actually isn't bad)
Then there is no need to run any of this...

**Comment by iklein99** [comment]
Going to close due to lack of activity.
