### ISSUE TITLE
Plug-in causes homebridge boot loop

### ISSUE THREAD

**Issue by pwlivewire** [iklein99/homebridge-smartthings#30]
Log is full of these before it reloads

[9/18/2022, 2:09:47 PM] Error: HAP Status
Error: -70402
at new HapStatusError /var/lib/homebr idge/node_modules/.pnpm/hap-nodejs@0.10.2/ node modules/hap-nodejs/src/lib/util/hapSt atusError.ts:15:5)
at /var/lib/homebridge/node_ modules/.p npm/homebridge-smartthings-ik@1.3.0/node_m odules/homebridge-smartthings-ik/src/senso rAccessory.ts:80:23
at new Promise (<anonymous>)
at SensorAccessory.requestStatus /var /lib/homebridge/node_modules/.pnpm/homebri dge-smartthings-ik@1.3.0/node_modules/home bridge-smartthings-ik/src/sensorAccessory.
ts:77:12)
at sensorAccessory.getMotion (/var/lib /homebridge/node_modules/.pnpm/homebridge-smartthings-ik@1.3.0/node_modules/homebrid ge-smartthings-ik/src/sensorAccessory.ts:1
09:37)
at Timeout.
onTimeout /var/lib/homebr
idge/node_modules/.pnpm/homebridge-smartth ings-ik@1.3.0/node_ modules/homebridge-smar tthings-ik/src/sensorAccessory.ts:56:14)
at listOnTimeout node:internal/timers
:559:17)
at processTimers node:internal/timers
:502:7)

**Comment by pwlivewire** [comment]
![image](https://user-images.githubusercontent.com/25018910/190904043-4e0a8837-e690-4cf9-85ad-f20f10a9c2f1.png)

**Comment by martindinicolino** [comment]
same here, any solutions?

**Comment by iklein99** [comment]
I’ll have a look at this today. Sent from my iPhoneOn Sep 19, 2022, at 5:23 AM, martindinicolino ***@***.***> wrote:﻿
same here, any solutions?

**Comment by iklein99** [comment]
There is a bug with the sensor code.  This is happening because your motion sensor is offline.  For now, you can exclude the device (see the readme for how to exclude devices) so that it doesn't try to register it.  I will get a fix out as soon as I can.

**Comment by iklein99** [comment]
Fixed in 1.3.1

**Comment by pwlivewire** [comment]
![image](https://user-images.githubusercontent.com/25018910/191142542-ebd78de0-3989-4a2a-a024-ee7d4c610d44.png)

Not fixed, just boot loops with a different error

**Comment by pwlivewire** [comment]
![image](https://user-images.githubusercontent.com/25018910/191142630-6cff6f0a-91d0-4e03-a408-61895b4f828b.png)
